### ISSUE TITLE
Provide Module Name

### ISSUE THREAD

**Issue by trensetim** [pac4j/javalin-pac4j#100]
I would really like to use your library in my modularized application.
Sadly you do not provide a module-info.java nor a Automatic-Module-Name in the manifest of your jar.

I suggest to make this ideally a real java module like

```
module javalin-pac4j {
  exports org.pac4j.javalin;
  requires transitive pac4j.core;
  requires pac4j.oidc;  // maybe?
}
```

**Comment by leleuj** [comment]
Please submit a PR.
