### ISSUE TITLE
When will the next version released?

### ISSUE THREAD

**Issue by estebanalvaradosanofi** [pac4j/javalin-pac4j#119]
Hi, I was wondering when the new version with Pac4J 5 will be available?

**Comment by leleuj** [comment]
I think everything is ready. I was waiting for some GO on this. I can release at any time.

Did you test the version 5.0.0-SNAPSHOT? Is it working?

**Comment by leleuj** [comment]
I just released javalin-pac4j v5.0.0. It will show up in the Maven central repository within a few hours/minutes.
