### ISSUE TITLE
[Help] Validating different roles / security requirements per endpoint

### ISSUE THREAD

**Issue by chrysophylax** [pac4j/javalin-pac4j#168]
Hi,

I can't seem to find the best way to do this in the documentation and I would appreciate any/all pointers if I've missed it!

My problem is the following:

I want to secure separate REST endpoints in the same javalin-pac4j application with different requirements.
I need to check for certain UserProfile claims in some cases (e.g. 'editor') but only check _isAuthenticated_  for other endpoints.
Do I need to create separate SecurityConfig with _separate_ handlers and add these to the Javalin Route configuration or is there way to use the same SecurityConfig and access several separate handlers at method/API route level?

A lot of the configuration is else reusable, the user will be submitting the same tokens, so it would be nice to avoid re-duplicating the security configs.

Best regards

**Comment by leleuj** [comment]
Please use the mailing lists for questions: https://www.pac4j.org/mailing-lists.html
