### ISSUE TITLE
Which version should I use ?

### ISSUE THREAD

**Issue by ermoca** [pac4j/javalin-pac4j#221]
Hello, 
I was wondering if you could help me figure out which version I should use.
I'm using javalin 5.6.2

I first tried to pair javalin-pac4j 6.0.0 with pac4j-oidc 6.0.0-RC8 but I got an error because it couldn't find the FindBest class that disappeared in pac4j-core 6.0.0-RC3 

I tried pac4j-oidc 6.0.0-RC7 having seen the "Make compatible with pac4j 6.0.0-RC7" merge but still get the same error

with  javalin-pac4j 6.0.0 and pac4j-oidc 6.0.0-RC2, I get  java.lang.NoSuchMethodError: org.pac4j.core.context.session.SessionStore org.pac4j.core.util.FindBest.sessionStore

I also tried to use javalin-pac4j 5.0.1 and pac4j-oidc 5.5.0 as stated by the README but I get an error "java.lang.NoSuchFieldError: req at org.pac4j.javalin.JavalinWebContext"

Thanks for your help  and have a nice day !

**Comment by ermoca** [comment]
Of course once I posted this issue I finally had the idea to check the previously closed one and saw that I should use 6.0.0 with 5.7.0

**Comment by tasosioannidis** [comment]
> Of course once I posted this issue I finally had the idea to check the previously closed one and saw that I should use 6.0.0 with 5.7.0

@edelagnier hi, 
Do you mean javalin-pac4j 6.0.0 which uses pac4j-core 5.7.0?
If that's correct and all work for you, could you share your other dependencies, like pac4j-http, pac4j-jwt, etc..?

Maybe also you are using code from:
https://github.com/pac4j/javalin-pac4j/blob/master/src/test/java/org/pac4j/javalin/example/JavalinPac4jExample.java
